language: php

php:
  - 5.4
  - 5.5

before_script:
  - sh -c "pear channel-discover pear.cakephp.org"
  - sh -c "composer require 'cakephp/cakephp-codesniffer:dev-master'"
  - sh -c "pear install --alldeps cakephp/CakePHP_CodeSniffer"
  - phpenv rehash

script:
  - sh -c "vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./App ./Test ./webroot"

notifications:
  email: false
